name: Publish to PyPI
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Run the same quality checks as CI
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install ruff build twine
          # Install PyTorch first to avoid dependency conflicts
          pip install "torch>=2.1" --index-url https://download.pytorch.org/whl/cpu
          pip install "pyro-ppl>=1.9"
          
      - name: Lint
        run: |
          ruff check src/ tests/
          ruff format --check src/ tests/
          
      - name: Test
        run: |
          pip install -e ".[test]"
          pytest tests/ -v --tb=short
          
      - name: Build
        run: python -m build
        
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
